### ISSUE TITLE
RTC callback is not fired after power_soc_sleep() or power_soc_deep_sleep()

### ISSUE THREAD

**Issue by keton** [quark-mcu/qmsi#12]
Maybe not an issue but I've noticed that if I have RTC callback that should fire on pending alarm set by qm_rtc_set_alarm() it works fine with power_soc_halt() but not with sleep() or deep_sleep(). CPU wakes fine but callback function never starts. 

For example consider attached program [rtc_blink.zip](https://github.com/quark-mcu/qmsi/files/545693/rtc_blink.zip). In provided form it works ok, you have both messages sent over UART and LED blinks every second but if you replace power_soc_halt() with one of sleep functions there's no callback.

**Comment by jeez** [comment]
@keton which SoC and platform are you using, please?

**Comment by keton** [comment]
I'm using official QuarkD2000 dev board with latest ISSM on Windows plus qmsi 1.2.0 release downloaded from GitHub

**Comment by jeez** [comment]
thanks for elaborating, @keton.

@mprinn can you please have a look at this issue? Do you know if this is something that is already fixed for the next major release by any chance?

**Comment by mprinn** [comment]
Hi @keton,
This issue should be fixed for 1.4, the patch to fix it missed the 1.3 window unfortunately.
What I know of it is that the ISR is triggered and the system state has not been fully restored which causes issues.

We're working out the flow in which the entire system state is restored before user code is executed.

**Comment by keton** [comment]
Is there by any chance something I can do in my code to fix this? I've been tasked with making a demo using Quark D2000 and some I2C peripherals and I really need working GPIO, RTC and I2C interrupts with ability to cut somewhat power consumption because everything will run from a 200mAh coin cell battery. So far either I don't use any form of sleep mode and get >4mA of power draw or I use sleep function and get very nice 20 uA but everything falls apart on wakeup.

**Comment by jeez** [comment]
I believe this issue will be fixed by PR https://github.com/quark-mcu/qmsi/pull/15 :).

**Comment by jeez** [comment]
@keton is this fixed now for you on the 1.3.1 release?

**Comment by keton** [comment]
It's fixed in 1.3.1. My blink example works as expected with power_soc_sleep().
